"""
ROE Gate Alerting — Slack and Webhook Notifications

Sends real-time alerts when the Gate makes enforcement decisions.
Supports Slack webhooks, generic HTTP webhooks, and configurable
alert thresholds.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import logging
import threading
import urllib.request
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from enum import Enum
from typing import Any


logger = logging.getLogger("roe_gate.alerting")


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------

class AlertLevel(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"

    def __ge__(self, other: AlertLevel) -> bool:
        order = {AlertLevel.INFO: 0, AlertLevel.WARNING: 1, AlertLevel.CRITICAL: 2}
        return order[self] >= order[other]

    def __gt__(self, other: AlertLevel) -> bool:
        order = {AlertLevel.INFO: 0, AlertLevel.WARNING: 1, AlertLevel.CRITICAL: 2}
        return order[self] > order[other]

    def __lt__(self, other: AlertLevel) -> bool:
        order = {AlertLevel.INFO: 0, AlertLevel.WARNING: 1, AlertLevel.CRITICAL: 2}
        return order[self] < order[other]

    def __le__(self, other: AlertLevel) -> bool:
        order = {AlertLevel.INFO: 0, AlertLevel.WARNING: 1, AlertLevel.CRITICAL: 2}
        return order[self] <= order[other]


@dataclass
class AlertEvent:
    """A single alert event generated by the Gate."""
    level: AlertLevel
    event_type: str
    summary: str
    details: dict[str, Any] = field(default_factory=dict)
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_dict(self) -> dict[str, Any]:
        return {
            "level": self.level.value,
            "event_type": self.event_type,
            "summary": self.summary,
            "details": self.details,
            "timestamp": self.timestamp,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), sort_keys=True, separators=(",", ":"))


# ---------------------------------------------------------------------------
# Alerters
# ---------------------------------------------------------------------------

_SLACK_COLORS = {
    "ALLOW": "#2eb886",   # green
    "DENY": "#cc0000",    # red
    "HALT": "#ffcc00",    # yellow
    "ESCALATE": "#ff9900",  # orange
}

_LEVEL_EMOJI = {
    AlertLevel.INFO: ":information_source:",
    AlertLevel.WARNING: ":warning:",
    AlertLevel.CRITICAL: ":rotating_light:",
}


class SlackAlerter:
    """Send alerts to a Slack incoming webhook."""

    def __init__(self, webhook_url: str) -> None:
        self.webhook_url = webhook_url

    def send(self, event: AlertEvent) -> None:
        """POST a formatted message to the Slack webhook.

        Uses threading so the Gate is never blocked waiting on Slack.
        """
        thread = threading.Thread(
            target=self._send_sync,
            args=(event,),
            daemon=True,
        )
        thread.start()

    def _send_sync(self, event: AlertEvent) -> None:
        decision = event.details.get("decision", event.event_type)
        color = _SLACK_COLORS.get(decision, "#439fe0")
        emoji = _LEVEL_EMOJI.get(event.level, "")

        # Build human-readable fields from details
        fields: list[dict[str, Any]] = []
        skip_keys = {"message", "decision"}  # shown in text/title already
        for key, val in event.details.items():
            if key in skip_keys:
                continue
            fields.append({
                "title": key.replace("_", " ").title(),
                "value": str(val),
                "short": len(str(val)) < 40,
            })

        # Use message from details as text if available, otherwise summary
        text = event.details.get("message", "")

        attachment: dict[str, Any] = {
            "color": color,
            "title": f"{emoji} ROE Gate — {event.summary}",
            "text": text,
            "fields": fields if fields else None,
            "footer": f"Level: {event.level.value} | {event.timestamp}",
        }
        # Remove None fields
        attachment = {k: v for k, v in attachment.items() if v is not None}

        payload = json.dumps({"attachments": [attachment]}).encode("utf-8")

        req = urllib.request.Request(
            self.webhook_url,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            urllib.request.urlopen(req, timeout=10)
        except Exception:
            logger.exception("Failed to send Slack alert")


class WebhookAlerter:
    """Send alerts to a generic HTTP webhook endpoint."""

    def __init__(
        self,
        url: str,
        headers: dict[str, str] | None = None,
        secret: str | None = None,
    ) -> None:
        self.url = url
        self.headers = headers or {}
        self.secret = secret

    def send(self, event: AlertEvent) -> None:
        """POST the event as JSON to the webhook URL.

        Uses threading so the Gate is never blocked.
        """
        thread = threading.Thread(
            target=self._send_sync,
            args=(event,),
            daemon=True,
        )
        thread.start()

    def _send_sync(self, event: AlertEvent) -> None:
        body = event.to_json().encode("utf-8")

        req_headers: dict[str, str] = {
            "Content-Type": "application/json",
        }
        req_headers.update(self.headers)

        if self.secret:
            sig = hmac.new(
                self.secret.encode("utf-8"),
                body,
                hashlib.sha256,
            ).hexdigest()
            req_headers["X-ROE-Signature"] = f"sha256={sig}"

        req = urllib.request.Request(
            self.url,
            data=body,
            headers=req_headers,
            method="POST",
        )
        try:
            urllib.request.urlopen(req, timeout=10)
        except Exception:
            logger.exception("Failed to send webhook alert")


# ---------------------------------------------------------------------------
# Alert manager
# ---------------------------------------------------------------------------

class AlertManager:
    """Dispatches alerts to all registered alerters, respecting min-level filters."""

    def __init__(self) -> None:
        self._alerters: list[tuple[SlackAlerter | WebhookAlerter, AlertLevel]] = []

    def register(
        self,
        alerter: SlackAlerter | WebhookAlerter,
        min_level: AlertLevel = AlertLevel.INFO,
    ) -> None:
        """Register an alerter with an optional minimum level filter."""
        self._alerters.append((alerter, min_level))

    def alert(self, event: AlertEvent) -> None:
        """Dispatch an event to every alerter whose min_level is satisfied."""
        for alerter, min_level in self._alerters:
            if event.level >= min_level:
                alerter.send(event)

    @classmethod
    def from_config(cls, config: dict[str, Any]) -> AlertManager:
        """Build an AlertManager from a configuration dictionary.

        Expected shape::

            {
              "slack": {
                "webhook_url": "https://hooks.slack.com/...",
                "min_level": "WARNING"       # optional, default INFO
              },
              "webhooks": [
                {
                  "url": "https://siem.example.com/api/events",
                  "headers": {"Authorization": "Bearer ..."},
                  "secret": "my-hmac-secret",  # optional
                  "min_level": "INFO"          # optional, default INFO
                }
              ]
            }
        """
        manager = cls()

        slack_cfg = config.get("slack")
        if slack_cfg:
            alerter = SlackAlerter(webhook_url=slack_cfg["webhook_url"])
            level = AlertLevel(slack_cfg.get("min_level", "INFO"))
            manager.register(alerter, min_level=level)

        for wh in config.get("webhooks", []):
            alerter = WebhookAlerter(
                url=wh["url"],
                headers=wh.get("headers"),
                secret=wh.get("secret"),
            )
            level = AlertLevel(wh.get("min_level", "INFO"))
            manager.register(alerter, min_level=level)

        return manager


# ---------------------------------------------------------------------------
# Convenience helper
# ---------------------------------------------------------------------------

_DECISION_LEVEL = {
    "ALLOW": AlertLevel.INFO,
    "DENY": AlertLevel.WARNING,
    "HALT": AlertLevel.CRITICAL,
    "ESCALATE": AlertLevel.WARNING,
}


def gate_result_to_alert(intent: Any, result: Any) -> AlertEvent:
    """Convert a GateResult (and its originating ActionIntent) into an AlertEvent.

    Args:
        intent: An ``ActionIntent`` instance.
        result: A ``GateResult`` instance.

    Returns:
        An ``AlertEvent`` ready to be dispatched.
    """
    decision = result.decision.value if hasattr(result.decision, "value") else str(result.decision)
    level = _DECISION_LEVEL.get(decision, AlertLevel.WARNING)

    summary = f"{decision}: {intent.tool} -> {intent.target.host or 'unknown'}"

    details: dict[str, Any] = {
        "decision": decision,
        "tool": intent.tool,
        "category": intent.category.value if hasattr(intent.category, "value") else str(intent.category),
        "target_host": intent.target.host if hasattr(intent.target, "host") else "",
        "reasoning": result.reasoning,
        "intent_id": intent.intent_id,
    }
    if hasattr(result, "denial_count"):
        details["denial_count"] = result.denial_count

    return AlertEvent(
        level=level,
        event_type=f"gate_{decision.lower()}",
        summary=summary,
        details=details,
    )
