"""
White-Label Branding Configuration

Allows MSSP/OEM customers to customize the Gate's branding:
- Dashboard colors and logo
- Email templates
- Report headers/footers
- API response branding
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class BrandingConfig:
    company_name: str = "ROE Gate"
    logo_url: str | None = None
    primary_color: str = "#00ff41"
    accent_color: str = "#ffb000"
    background_color: str = "#0d1117"
    dashboard_title: str = "ROE Gate Dashboard"
    email_from_name: str = "ROE Gate"
    report_header: str = "ROE Gate Compliance Report"
    report_footer: str = "Generated by ROE Gate | Patent Pending"
    custom_css: str | None = None


class BrandingManager:
    """Manages per-tenant branding configurations with a global default."""

    def __init__(self, default_config: BrandingConfig | None = None) -> None:
        self._default = default_config or BrandingConfig()
        self._tenant_configs: dict[str, BrandingConfig] = {}

    # ------------------------------------------------------------------
    # Config management
    # ------------------------------------------------------------------

    def set_branding(self, tenant_id: str, config: BrandingConfig) -> None:
        """Set branding for a specific tenant."""
        self._tenant_configs[tenant_id] = config

    def get_branding(self, tenant_id: str | None = None) -> BrandingConfig:
        """Return tenant-specific branding or the default."""
        if tenant_id and tenant_id in self._tenant_configs:
            return self._tenant_configs[tenant_id]
        return self._default

    # ------------------------------------------------------------------
    # Dashboard integration
    # ------------------------------------------------------------------

    def apply_to_dashboard_html(
        self, html: str, tenant_id: str | None = None
    ) -> str:
        """Replace placeholders in dashboard HTML with branding values."""
        cfg = self.get_branding(tenant_id)
        replacements = {
            "{{company_name}}": cfg.company_name,
            "{{logo_url}}": cfg.logo_url or "",
            "{{primary_color}}": cfg.primary_color,
            "{{accent_color}}": cfg.accent_color,
            "{{background_color}}": cfg.background_color,
            "{{dashboard_title}}": cfg.dashboard_title,
            "{{email_from_name}}": cfg.email_from_name,
            "{{report_header}}": cfg.report_header,
            "{{report_footer}}": cfg.report_footer,
        }
        result = html
        for placeholder, value in replacements.items():
            result = result.replace(placeholder, value)

        # Inject custom CSS if present
        if cfg.custom_css and "</head>" in result:
            result = result.replace(
                "</head>",
                f"<style>{cfg.custom_css}</style></head>",
            )

        return result

    # ------------------------------------------------------------------
    # Serialization
    # ------------------------------------------------------------------

    def to_dict(self, tenant_id: str | None = None) -> dict:
        """Export branding config as a dictionary."""
        cfg = self.get_branding(tenant_id)
        return {
            "company_name": cfg.company_name,
            "logo_url": cfg.logo_url,
            "primary_color": cfg.primary_color,
            "accent_color": cfg.accent_color,
            "background_color": cfg.background_color,
            "dashboard_title": cfg.dashboard_title,
            "email_from_name": cfg.email_from_name,
            "report_header": cfg.report_header,
            "report_footer": cfg.report_footer,
            "custom_css": cfg.custom_css,
        }

    @staticmethod
    def from_dict(data: dict) -> BrandingConfig:
        """Create a BrandingConfig from a dictionary."""
        return BrandingConfig(
            company_name=data.get("company_name", "ROE Gate"),
            logo_url=data.get("logo_url"),
            primary_color=data.get("primary_color", "#00ff41"),
            accent_color=data.get("accent_color", "#ffb000"),
            background_color=data.get("background_color", "#0d1117"),
            dashboard_title=data.get("dashboard_title", "ROE Gate Dashboard"),
            email_from_name=data.get("email_from_name", "ROE Gate"),
            report_header=data.get("report_header", "ROE Gate Compliance Report"),
            report_footer=data.get(
                "report_footer", "Generated by ROE Gate | Patent Pending"
            ),
            custom_css=data.get("custom_css"),
        )
