"""Tests for White-Label Branding Configuration."""

from src.service.branding import BrandingConfig, BrandingManager


class TestBrandingDefaults:
    def test_default_config_values(self) -> None:
        cfg = BrandingConfig()
        assert cfg.company_name == "ROE Gate"
        assert cfg.primary_color == "#00ff41"
        assert cfg.accent_color == "#ffb000"
        assert cfg.background_color == "#0d1117"
        assert cfg.dashboard_title == "ROE Gate Dashboard"
        assert cfg.email_from_name == "ROE Gate"
        assert cfg.report_header == "ROE Gate Compliance Report"
        assert cfg.report_footer == "Generated by ROE Gate | Patent Pending"
        assert cfg.logo_url is None
        assert cfg.custom_css is None

    def test_get_branding_returns_default_when_no_tenant(self) -> None:
        mgr = BrandingManager()
        cfg = mgr.get_branding()
        assert cfg.company_name == "ROE Gate"

    def test_get_branding_falls_back_to_default_for_unknown_tenant(self) -> None:
        mgr = BrandingManager()
        cfg = mgr.get_branding(tenant_id="unknown-tenant")
        assert cfg.company_name == "ROE Gate"


class TestPerTenantBranding:
    def test_set_and_get_tenant_branding(self) -> None:
        mgr = BrandingManager()
        custom = BrandingConfig(
            company_name="SecureCo",
            primary_color="#ff0000",
            dashboard_title="SecureCo Dashboard",
        )
        mgr.set_branding("tenant-1", custom)
        cfg = mgr.get_branding("tenant-1")
        assert cfg.company_name == "SecureCo"
        assert cfg.primary_color == "#ff0000"
        assert cfg.dashboard_title == "SecureCo Dashboard"

    def test_different_tenants_have_different_branding(self) -> None:
        mgr = BrandingManager()
        mgr.set_branding("t1", BrandingConfig(company_name="Alpha"))
        mgr.set_branding("t2", BrandingConfig(company_name="Beta"))
        assert mgr.get_branding("t1").company_name == "Alpha"
        assert mgr.get_branding("t2").company_name == "Beta"


class TestDashboardHTML:
    def test_apply_to_dashboard_html_replaces_placeholders(self) -> None:
        mgr = BrandingManager()
        html = "<title>{{dashboard_title}}</title><h1>{{company_name}}</h1>"
        result = mgr.apply_to_dashboard_html(html)
        assert "ROE Gate Dashboard" in result
        assert "ROE Gate" in result
        assert "{{dashboard_title}}" not in result
        assert "{{company_name}}" not in result

    def test_apply_uses_tenant_branding(self) -> None:
        mgr = BrandingManager()
        mgr.set_branding("t1", BrandingConfig(company_name="SecureCo"))
        html = "<h1>{{company_name}}</h1>"
        result = mgr.apply_to_dashboard_html(html, tenant_id="t1")
        assert "SecureCo" in result

    def test_custom_css_injected_into_head(self) -> None:
        mgr = BrandingManager()
        custom = BrandingConfig(custom_css="body { font-size: 16px; }")
        mgr.set_branding("t1", custom)
        html = "<html><head></head><body></body></html>"
        result = mgr.apply_to_dashboard_html(html, tenant_id="t1")
        assert "<style>body { font-size: 16px; }</style></head>" in result

    def test_no_custom_css_leaves_html_unchanged(self) -> None:
        mgr = BrandingManager()
        html = "<html><head></head><body></body></html>"
        result = mgr.apply_to_dashboard_html(html)
        assert "<style>" not in result


class TestSerialization:
    def test_to_dict(self) -> None:
        mgr = BrandingManager()
        d = mgr.to_dict()
        assert d["company_name"] == "ROE Gate"
        assert d["primary_color"] == "#00ff41"
        assert d["custom_css"] is None

    def test_from_dict(self) -> None:
        data = {
            "company_name": "TestCo",
            "primary_color": "#123456",
            "logo_url": "https://example.com/logo.png",
        }
        cfg = BrandingManager.from_dict(data)
        assert cfg.company_name == "TestCo"
        assert cfg.primary_color == "#123456"
        assert cfg.logo_url == "https://example.com/logo.png"
        # Defaults for unset fields
        assert cfg.accent_color == "#ffb000"

    def test_to_dict_from_dict_round_trip(self) -> None:
        mgr = BrandingManager()
        custom = BrandingConfig(
            company_name="RoundTrip Co",
            primary_color="#abcdef",
            custom_css=".test { color: red; }",
        )
        mgr.set_branding("t1", custom)
        exported = mgr.to_dict("t1")
        restored = BrandingManager.from_dict(exported)
        assert restored.company_name == "RoundTrip Co"
        assert restored.primary_color == "#abcdef"
        assert restored.custom_css == ".test { color: red; }"
